version: '3.9'

services:
  web:
    image: python:3.11-slim
    container_name: libraflux-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir -r requirements.txt &&
             python main.py"